// resources/js/Components/Footer.vue
<script setup>
</script>
<template>
    <footer class="main-footer">
        <div class="footer-left">
            Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad
                Nauval Azhar</a>
        </div>
        <div class="footer-right">
            2.3.0
        </div>
    </footer>
</template>

// resources/js/components/Footer.jsx
export default function Footer() {
    return(
        <div>
            <footer className="main-footer">
                <div className="footer-left">
                    Copyright &copy; 2018 <div className="bullet"></div> Design By <a href="https://nauval.in/">Muhamad
                        Nauval Azhar</a>
                </div>
                <div className="footer-right">
                    2.3.0
                </div>
            </footer>    
        </div>
    );
}
